import Image from 'next/image';
import { Asterisk, ArrowUpRight, Search, Sparkles } from 'lucide-react';
export function ProjectVisual({slug}:{slug:string}){
 return <div className={'project-visual visual-'+slug} aria-hidden="true">
 {slug==='aetherfield'&&<><div className="aether-type"><div className="mini-brand"><Asterisk size={18}/> Aetherfield</div><span>Sustainability insights,<br/>built for business.</span><div className="mini-pill">Explore the platform <ArrowUpRight size={11}/></div></div><Image className="aether-photo" src="/projects/aetherfield.webp" alt="" width={750} height={750}/><div className="metric-float"><span>ENERGY CONSUMPTION</span><strong>583.7 <small>MWh</small></strong><div className="bar-chart">{[32,54,41,65,55,72,48,39,57,43,30,24].map((v,i)=><i key={i} style={{height:v+'%'}}/>)}</div><span>TRACK. UNDERSTAND. ACT.</span></div></>}
 {slug==='studio-antenix'&&<><span className="studio-top">INDEPENDENT THINKING. DISTINCTIVE DESIGN.</span><div className="studio-type">Studio<br/><em>Antenix</em><Asterisk/></div><Image className="studio-photo" src="/projects/antenix.webp" alt="" width={405} height={487}/><div className="studio-bottom">STRATEGY × DESIGN × EXPERIENCE <ArrowUpRight size={25}/></div></>}
 {slug==='jobbiton'&&<><div className="job-type"><span className="mini-brand">jobbiton<span className="job-dot">✳</span></span><strong>Your next chapter.<br/>A clearer path.</strong></div><Image className="job-dashboard-image" src="/projects/jobbiton.webp" alt="" width={3840} height={1938}/><span className="visual-disclaimer">LIVE PRODUCT / DASHBOARD PREVIEW</span></>}
 {slug==='pixca'&&<><div className="pixca-masthead">pixca<span>DAILY</span></div><div className="pixca-nav">YOUR DAILY PERSPECTIVE <span>NEWS, IN FOCUS.</span></div><div className="pixca-layout"><div><span className="pixca-category">THE BIG PICTURE</span><h4>A world of stories.<br/>A clearer perspective.</h4><p>Ideas, discoveries, and the stories<br/>shaping what comes next.</p></div><div className="pixca-stack"><Image className="pixca-photo" src="/projects/pixca.jpg" alt="" width={1024} height={576}/>{['Technology & innovation','Culture & creativity','Our changing world'].map((x,i)=><div key={x}><span>0{i+1}</span>{x}<ArrowUpRight size={15}/></div>)}</div></div><span className="visual-disclaimer">IMAGE FROM PIXCA’S NEWS FEED</span></>}
 {slug==='ether'&&<><Image className="ether-photo" src="/projects/ether.webp" alt="" width={1060} height={606}/><div className="ether-shade"/><div className="ether-type"><span className="mini-brand">ether<span>®</span></span><strong>Imagine it.<br/><em>Make it real.</em></strong><div className="ether-prompt"><Sparkles size={16}/> A little imagination goes a long way <ArrowUpRight size={16}/></div></div></>}
 </div>
}
